
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Method` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Method
 * 
 */
export type MethodModel = runtime.Types.Result.DefaultSelection<Prisma.$MethodPayload>

export type AggregateMethod = {
  _count: MethodCountAggregateOutputType | null
  _avg: MethodAvgAggregateOutputType | null
  _sum: MethodSumAggregateOutputType | null
  _min: MethodMinAggregateOutputType | null
  _max: MethodMaxAggregateOutputType | null
}

export type MethodAvgAggregateOutputType = {
  id: number | null
}

export type MethodSumAggregateOutputType = {
  id: number | null
}

export type MethodMinAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
}

export type MethodMaxAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
}

export type MethodCountAggregateOutputType = {
  id: number
  name: number
  description: number
  _all: number
}


export type MethodAvgAggregateInputType = {
  id?: true
}

export type MethodSumAggregateInputType = {
  id?: true
}

export type MethodMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
}

export type MethodMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
}

export type MethodCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  _all?: true
}

export type MethodAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Method to aggregate.
   */
  where?: Prisma.MethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Methods to fetch.
   */
  orderBy?: Prisma.MethodOrderByWithRelationInput | Prisma.MethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Methods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Methods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Methods
  **/
  _count?: true | MethodCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MethodAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MethodSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MethodMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MethodMaxAggregateInputType
}

export type GetMethodAggregateType<T extends MethodAggregateArgs> = {
      [P in keyof T & keyof AggregateMethod]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMethod[P]>
    : Prisma.GetScalarType<T[P], AggregateMethod[P]>
}




export type MethodGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MethodWhereInput
  orderBy?: Prisma.MethodOrderByWithAggregationInput | Prisma.MethodOrderByWithAggregationInput[]
  by: Prisma.MethodScalarFieldEnum[] | Prisma.MethodScalarFieldEnum
  having?: Prisma.MethodScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MethodCountAggregateInputType | true
  _avg?: MethodAvgAggregateInputType
  _sum?: MethodSumAggregateInputType
  _min?: MethodMinAggregateInputType
  _max?: MethodMaxAggregateInputType
}

export type MethodGroupByOutputType = {
  id: number
  name: string
  description: string
  _count: MethodCountAggregateOutputType | null
  _avg: MethodAvgAggregateOutputType | null
  _sum: MethodSumAggregateOutputType | null
  _min: MethodMinAggregateOutputType | null
  _max: MethodMaxAggregateOutputType | null
}

export type GetMethodGroupByPayload<T extends MethodGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MethodGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MethodGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MethodGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MethodGroupByOutputType[P]>
      }
    >
  >



export type MethodWhereInput = {
  AND?: Prisma.MethodWhereInput | Prisma.MethodWhereInput[]
  OR?: Prisma.MethodWhereInput[]
  NOT?: Prisma.MethodWhereInput | Prisma.MethodWhereInput[]
  id?: Prisma.IntFilter<"Method"> | number
  name?: Prisma.StringFilter<"Method"> | string
  description?: Prisma.StringFilter<"Method"> | string
}

export type MethodOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type MethodWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MethodWhereInput | Prisma.MethodWhereInput[]
  OR?: Prisma.MethodWhereInput[]
  NOT?: Prisma.MethodWhereInput | Prisma.MethodWhereInput[]
  name?: Prisma.StringFilter<"Method"> | string
  description?: Prisma.StringFilter<"Method"> | string
}, "id">

export type MethodOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  _count?: Prisma.MethodCountOrderByAggregateInput
  _avg?: Prisma.MethodAvgOrderByAggregateInput
  _max?: Prisma.MethodMaxOrderByAggregateInput
  _min?: Prisma.MethodMinOrderByAggregateInput
  _sum?: Prisma.MethodSumOrderByAggregateInput
}

export type MethodScalarWhereWithAggregatesInput = {
  AND?: Prisma.MethodScalarWhereWithAggregatesInput | Prisma.MethodScalarWhereWithAggregatesInput[]
  OR?: Prisma.MethodScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MethodScalarWhereWithAggregatesInput | Prisma.MethodScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Method"> | number
  name?: Prisma.StringWithAggregatesFilter<"Method"> | string
  description?: Prisma.StringWithAggregatesFilter<"Method"> | string
}

export type MethodCreateInput = {
  name: string
  description: string
}

export type MethodUncheckedCreateInput = {
  id?: number
  name: string
  description: string
}

export type MethodUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MethodUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MethodCreateManyInput = {
  id?: number
  name: string
  description: string
}

export type MethodUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MethodUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MethodCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type MethodAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type MethodMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type MethodMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type MethodSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type MethodSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
}, ExtArgs["result"]["method"]>

export type MethodSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
}, ExtArgs["result"]["method"]>

export type MethodSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
}, ExtArgs["result"]["method"]>

export type MethodSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
}

export type MethodOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description", ExtArgs["result"]["method"]>

export type $MethodPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Method"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    description: string
  }, ExtArgs["result"]["method"]>
  composites: {}
}

export type MethodGetPayload<S extends boolean | null | undefined | MethodDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MethodPayload, S>

export type MethodCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MethodFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MethodCountAggregateInputType | true
  }

export interface MethodDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Method'], meta: { name: 'Method' } }
  /**
   * Find zero or one Method that matches the filter.
   * @param {MethodFindUniqueArgs} args - Arguments to find a Method
   * @example
   * // Get one Method
   * const method = await prisma.method.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MethodFindUniqueArgs>(args: Prisma.SelectSubset<T, MethodFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MethodClient<runtime.Types.Result.GetResult<Prisma.$MethodPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Method that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MethodFindUniqueOrThrowArgs} args - Arguments to find a Method
   * @example
   * // Get one Method
   * const method = await prisma.method.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MethodFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MethodFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MethodClient<runtime.Types.Result.GetResult<Prisma.$MethodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Method that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MethodFindFirstArgs} args - Arguments to find a Method
   * @example
   * // Get one Method
   * const method = await prisma.method.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MethodFindFirstArgs>(args?: Prisma.SelectSubset<T, MethodFindFirstArgs<ExtArgs>>): Prisma.Prisma__MethodClient<runtime.Types.Result.GetResult<Prisma.$MethodPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Method that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MethodFindFirstOrThrowArgs} args - Arguments to find a Method
   * @example
   * // Get one Method
   * const method = await prisma.method.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MethodFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MethodFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MethodClient<runtime.Types.Result.GetResult<Prisma.$MethodPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Methods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MethodFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Methods
   * const methods = await prisma.method.findMany()
   * 
   * // Get first 10 Methods
   * const methods = await prisma.method.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const methodWithIdOnly = await prisma.method.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MethodFindManyArgs>(args?: Prisma.SelectSubset<T, MethodFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MethodPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Method.
   * @param {MethodCreateArgs} args - Arguments to create a Method.
   * @example
   * // Create one Method
   * const Method = await prisma.method.create({
   *   data: {
   *     // ... data to create a Method
   *   }
   * })
   * 
   */
  create<T extends MethodCreateArgs>(args: Prisma.SelectSubset<T, MethodCreateArgs<ExtArgs>>): Prisma.Prisma__MethodClient<runtime.Types.Result.GetResult<Prisma.$MethodPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Methods.
   * @param {MethodCreateManyArgs} args - Arguments to create many Methods.
   * @example
   * // Create many Methods
   * const method = await prisma.method.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MethodCreateManyArgs>(args?: Prisma.SelectSubset<T, MethodCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Methods and returns the data saved in the database.
   * @param {MethodCreateManyAndReturnArgs} args - Arguments to create many Methods.
   * @example
   * // Create many Methods
   * const method = await prisma.method.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Methods and only return the `id`
   * const methodWithIdOnly = await prisma.method.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MethodCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MethodCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MethodPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Method.
   * @param {MethodDeleteArgs} args - Arguments to delete one Method.
   * @example
   * // Delete one Method
   * const Method = await prisma.method.delete({
   *   where: {
   *     // ... filter to delete one Method
   *   }
   * })
   * 
   */
  delete<T extends MethodDeleteArgs>(args: Prisma.SelectSubset<T, MethodDeleteArgs<ExtArgs>>): Prisma.Prisma__MethodClient<runtime.Types.Result.GetResult<Prisma.$MethodPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Method.
   * @param {MethodUpdateArgs} args - Arguments to update one Method.
   * @example
   * // Update one Method
   * const method = await prisma.method.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MethodUpdateArgs>(args: Prisma.SelectSubset<T, MethodUpdateArgs<ExtArgs>>): Prisma.Prisma__MethodClient<runtime.Types.Result.GetResult<Prisma.$MethodPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Methods.
   * @param {MethodDeleteManyArgs} args - Arguments to filter Methods to delete.
   * @example
   * // Delete a few Methods
   * const { count } = await prisma.method.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MethodDeleteManyArgs>(args?: Prisma.SelectSubset<T, MethodDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Methods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MethodUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Methods
   * const method = await prisma.method.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MethodUpdateManyArgs>(args: Prisma.SelectSubset<T, MethodUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Methods and returns the data updated in the database.
   * @param {MethodUpdateManyAndReturnArgs} args - Arguments to update many Methods.
   * @example
   * // Update many Methods
   * const method = await prisma.method.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Methods and only return the `id`
   * const methodWithIdOnly = await prisma.method.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MethodUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MethodUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MethodPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Method.
   * @param {MethodUpsertArgs} args - Arguments to update or create a Method.
   * @example
   * // Update or create a Method
   * const method = await prisma.method.upsert({
   *   create: {
   *     // ... data to create a Method
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Method we want to update
   *   }
   * })
   */
  upsert<T extends MethodUpsertArgs>(args: Prisma.SelectSubset<T, MethodUpsertArgs<ExtArgs>>): Prisma.Prisma__MethodClient<runtime.Types.Result.GetResult<Prisma.$MethodPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Methods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MethodCountArgs} args - Arguments to filter Methods to count.
   * @example
   * // Count the number of Methods
   * const count = await prisma.method.count({
   *   where: {
   *     // ... the filter for the Methods we want to count
   *   }
   * })
  **/
  count<T extends MethodCountArgs>(
    args?: Prisma.Subset<T, MethodCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MethodCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Method.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MethodAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MethodAggregateArgs>(args: Prisma.Subset<T, MethodAggregateArgs>): Prisma.PrismaPromise<GetMethodAggregateType<T>>

  /**
   * Group by Method.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MethodGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MethodGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MethodGroupByArgs['orderBy'] }
      : { orderBy?: MethodGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MethodGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMethodGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Method model
 */
readonly fields: MethodFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Method.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MethodClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Method model
 */
export interface MethodFieldRefs {
  readonly id: Prisma.FieldRef<"Method", 'Int'>
  readonly name: Prisma.FieldRef<"Method", 'String'>
  readonly description: Prisma.FieldRef<"Method", 'String'>
}
    

// Custom InputTypes
/**
 * Method findUnique
 */
export type MethodFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Method
   */
  select?: Prisma.MethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Method
   */
  omit?: Prisma.MethodOmit<ExtArgs> | null
  /**
   * Filter, which Method to fetch.
   */
  where: Prisma.MethodWhereUniqueInput
}

/**
 * Method findUniqueOrThrow
 */
export type MethodFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Method
   */
  select?: Prisma.MethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Method
   */
  omit?: Prisma.MethodOmit<ExtArgs> | null
  /**
   * Filter, which Method to fetch.
   */
  where: Prisma.MethodWhereUniqueInput
}

/**
 * Method findFirst
 */
export type MethodFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Method
   */
  select?: Prisma.MethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Method
   */
  omit?: Prisma.MethodOmit<ExtArgs> | null
  /**
   * Filter, which Method to fetch.
   */
  where?: Prisma.MethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Methods to fetch.
   */
  orderBy?: Prisma.MethodOrderByWithRelationInput | Prisma.MethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Methods.
   */
  cursor?: Prisma.MethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Methods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Methods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Methods.
   */
  distinct?: Prisma.MethodScalarFieldEnum | Prisma.MethodScalarFieldEnum[]
}

/**
 * Method findFirstOrThrow
 */
export type MethodFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Method
   */
  select?: Prisma.MethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Method
   */
  omit?: Prisma.MethodOmit<ExtArgs> | null
  /**
   * Filter, which Method to fetch.
   */
  where?: Prisma.MethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Methods to fetch.
   */
  orderBy?: Prisma.MethodOrderByWithRelationInput | Prisma.MethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Methods.
   */
  cursor?: Prisma.MethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Methods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Methods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Methods.
   */
  distinct?: Prisma.MethodScalarFieldEnum | Prisma.MethodScalarFieldEnum[]
}

/**
 * Method findMany
 */
export type MethodFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Method
   */
  select?: Prisma.MethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Method
   */
  omit?: Prisma.MethodOmit<ExtArgs> | null
  /**
   * Filter, which Methods to fetch.
   */
  where?: Prisma.MethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Methods to fetch.
   */
  orderBy?: Prisma.MethodOrderByWithRelationInput | Prisma.MethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Methods.
   */
  cursor?: Prisma.MethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Methods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Methods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Methods.
   */
  distinct?: Prisma.MethodScalarFieldEnum | Prisma.MethodScalarFieldEnum[]
}

/**
 * Method create
 */
export type MethodCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Method
   */
  select?: Prisma.MethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Method
   */
  omit?: Prisma.MethodOmit<ExtArgs> | null
  /**
   * The data needed to create a Method.
   */
  data: Prisma.XOR<Prisma.MethodCreateInput, Prisma.MethodUncheckedCreateInput>
}

/**
 * Method createMany
 */
export type MethodCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Methods.
   */
  data: Prisma.MethodCreateManyInput | Prisma.MethodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Method createManyAndReturn
 */
export type MethodCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Method
   */
  select?: Prisma.MethodSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Method
   */
  omit?: Prisma.MethodOmit<ExtArgs> | null
  /**
   * The data used to create many Methods.
   */
  data: Prisma.MethodCreateManyInput | Prisma.MethodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Method update
 */
export type MethodUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Method
   */
  select?: Prisma.MethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Method
   */
  omit?: Prisma.MethodOmit<ExtArgs> | null
  /**
   * The data needed to update a Method.
   */
  data: Prisma.XOR<Prisma.MethodUpdateInput, Prisma.MethodUncheckedUpdateInput>
  /**
   * Choose, which Method to update.
   */
  where: Prisma.MethodWhereUniqueInput
}

/**
 * Method updateMany
 */
export type MethodUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Methods.
   */
  data: Prisma.XOR<Prisma.MethodUpdateManyMutationInput, Prisma.MethodUncheckedUpdateManyInput>
  /**
   * Filter which Methods to update
   */
  where?: Prisma.MethodWhereInput
  /**
   * Limit how many Methods to update.
   */
  limit?: number
}

/**
 * Method updateManyAndReturn
 */
export type MethodUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Method
   */
  select?: Prisma.MethodSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Method
   */
  omit?: Prisma.MethodOmit<ExtArgs> | null
  /**
   * The data used to update Methods.
   */
  data: Prisma.XOR<Prisma.MethodUpdateManyMutationInput, Prisma.MethodUncheckedUpdateManyInput>
  /**
   * Filter which Methods to update
   */
  where?: Prisma.MethodWhereInput
  /**
   * Limit how many Methods to update.
   */
  limit?: number
}

/**
 * Method upsert
 */
export type MethodUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Method
   */
  select?: Prisma.MethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Method
   */
  omit?: Prisma.MethodOmit<ExtArgs> | null
  /**
   * The filter to search for the Method to update in case it exists.
   */
  where: Prisma.MethodWhereUniqueInput
  /**
   * In case the Method found by the `where` argument doesn't exist, create a new Method with this data.
   */
  create: Prisma.XOR<Prisma.MethodCreateInput, Prisma.MethodUncheckedCreateInput>
  /**
   * In case the Method was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MethodUpdateInput, Prisma.MethodUncheckedUpdateInput>
}

/**
 * Method delete
 */
export type MethodDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Method
   */
  select?: Prisma.MethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Method
   */
  omit?: Prisma.MethodOmit<ExtArgs> | null
  /**
   * Filter which Method to delete.
   */
  where: Prisma.MethodWhereUniqueInput
}

/**
 * Method deleteMany
 */
export type MethodDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Methods to delete
   */
  where?: Prisma.MethodWhereInput
  /**
   * Limit how many Methods to delete.
   */
  limit?: number
}

/**
 * Method without action
 */
export type MethodDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Method
   */
  select?: Prisma.MethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Method
   */
  omit?: Prisma.MethodOmit<ExtArgs> | null
}
