
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Seat` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Seat
 * 
 */
export type SeatModel = runtime.Types.Result.DefaultSelection<Prisma.$SeatPayload>

export type AggregateSeat = {
  _count: SeatCountAggregateOutputType | null
  _avg: SeatAvgAggregateOutputType | null
  _sum: SeatSumAggregateOutputType | null
  _min: SeatMinAggregateOutputType | null
  _max: SeatMaxAggregateOutputType | null
}

export type SeatAvgAggregateOutputType = {
  id: number | null
  trip_id: number | null
  seat_class_id: number | null
}

export type SeatSumAggregateOutputType = {
  id: number | null
  trip_id: number | null
  seat_class_id: number | null
}

export type SeatMinAggregateOutputType = {
  id: number | null
  status: $Enums.SeatStatus | null
  trip_id: number | null
  created_at: Date | null
  updated_at: Date | null
  seat_class_id: number | null
}

export type SeatMaxAggregateOutputType = {
  id: number | null
  status: $Enums.SeatStatus | null
  trip_id: number | null
  created_at: Date | null
  updated_at: Date | null
  seat_class_id: number | null
}

export type SeatCountAggregateOutputType = {
  id: number
  status: number
  trip_id: number
  created_at: number
  updated_at: number
  seat_class_id: number
  _all: number
}


export type SeatAvgAggregateInputType = {
  id?: true
  trip_id?: true
  seat_class_id?: true
}

export type SeatSumAggregateInputType = {
  id?: true
  trip_id?: true
  seat_class_id?: true
}

export type SeatMinAggregateInputType = {
  id?: true
  status?: true
  trip_id?: true
  created_at?: true
  updated_at?: true
  seat_class_id?: true
}

export type SeatMaxAggregateInputType = {
  id?: true
  status?: true
  trip_id?: true
  created_at?: true
  updated_at?: true
  seat_class_id?: true
}

export type SeatCountAggregateInputType = {
  id?: true
  status?: true
  trip_id?: true
  created_at?: true
  updated_at?: true
  seat_class_id?: true
  _all?: true
}

export type SeatAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Seat to aggregate.
   */
  where?: Prisma.SeatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seats to fetch.
   */
  orderBy?: Prisma.SeatOrderByWithRelationInput | Prisma.SeatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SeatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Seats
  **/
  _count?: true | SeatCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SeatAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SeatSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SeatMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SeatMaxAggregateInputType
}

export type GetSeatAggregateType<T extends SeatAggregateArgs> = {
      [P in keyof T & keyof AggregateSeat]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSeat[P]>
    : Prisma.GetScalarType<T[P], AggregateSeat[P]>
}




export type SeatGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SeatWhereInput
  orderBy?: Prisma.SeatOrderByWithAggregationInput | Prisma.SeatOrderByWithAggregationInput[]
  by: Prisma.SeatScalarFieldEnum[] | Prisma.SeatScalarFieldEnum
  having?: Prisma.SeatScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SeatCountAggregateInputType | true
  _avg?: SeatAvgAggregateInputType
  _sum?: SeatSumAggregateInputType
  _min?: SeatMinAggregateInputType
  _max?: SeatMaxAggregateInputType
}

export type SeatGroupByOutputType = {
  id: number
  status: $Enums.SeatStatus
  trip_id: number
  created_at: Date
  updated_at: Date
  seat_class_id: number
  _count: SeatCountAggregateOutputType | null
  _avg: SeatAvgAggregateOutputType | null
  _sum: SeatSumAggregateOutputType | null
  _min: SeatMinAggregateOutputType | null
  _max: SeatMaxAggregateOutputType | null
}

export type GetSeatGroupByPayload<T extends SeatGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SeatGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SeatGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SeatGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SeatGroupByOutputType[P]>
      }
    >
  >



export type SeatWhereInput = {
  AND?: Prisma.SeatWhereInput | Prisma.SeatWhereInput[]
  OR?: Prisma.SeatWhereInput[]
  NOT?: Prisma.SeatWhereInput | Prisma.SeatWhereInput[]
  id?: Prisma.IntFilter<"Seat"> | number
  status?: Prisma.EnumSeatStatusFilter<"Seat"> | $Enums.SeatStatus
  trip_id?: Prisma.IntFilter<"Seat"> | number
  created_at?: Prisma.DateTimeFilter<"Seat"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Seat"> | Date | string
  seat_class_id?: Prisma.IntFilter<"Seat"> | number
  seat_class?: Prisma.XOR<Prisma.SeatClassScalarRelationFilter, Prisma.SeatClassWhereInput>
  ticket?: Prisma.XOR<Prisma.TicketNullableScalarRelationFilter, Prisma.TicketWhereInput> | null
  trip?: Prisma.XOR<Prisma.TripScalarRelationFilter, Prisma.TripWhereInput>
}

export type SeatOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  trip_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  seat_class_id?: Prisma.SortOrder
  seat_class?: Prisma.SeatClassOrderByWithRelationInput
  ticket?: Prisma.TicketOrderByWithRelationInput
  trip?: Prisma.TripOrderByWithRelationInput
}

export type SeatWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.SeatWhereInput | Prisma.SeatWhereInput[]
  OR?: Prisma.SeatWhereInput[]
  NOT?: Prisma.SeatWhereInput | Prisma.SeatWhereInput[]
  status?: Prisma.EnumSeatStatusFilter<"Seat"> | $Enums.SeatStatus
  trip_id?: Prisma.IntFilter<"Seat"> | number
  created_at?: Prisma.DateTimeFilter<"Seat"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Seat"> | Date | string
  seat_class_id?: Prisma.IntFilter<"Seat"> | number
  seat_class?: Prisma.XOR<Prisma.SeatClassScalarRelationFilter, Prisma.SeatClassWhereInput>
  ticket?: Prisma.XOR<Prisma.TicketNullableScalarRelationFilter, Prisma.TicketWhereInput> | null
  trip?: Prisma.XOR<Prisma.TripScalarRelationFilter, Prisma.TripWhereInput>
}, "id">

export type SeatOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  trip_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  seat_class_id?: Prisma.SortOrder
  _count?: Prisma.SeatCountOrderByAggregateInput
  _avg?: Prisma.SeatAvgOrderByAggregateInput
  _max?: Prisma.SeatMaxOrderByAggregateInput
  _min?: Prisma.SeatMinOrderByAggregateInput
  _sum?: Prisma.SeatSumOrderByAggregateInput
}

export type SeatScalarWhereWithAggregatesInput = {
  AND?: Prisma.SeatScalarWhereWithAggregatesInput | Prisma.SeatScalarWhereWithAggregatesInput[]
  OR?: Prisma.SeatScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SeatScalarWhereWithAggregatesInput | Prisma.SeatScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Seat"> | number
  status?: Prisma.EnumSeatStatusWithAggregatesFilter<"Seat"> | $Enums.SeatStatus
  trip_id?: Prisma.IntWithAggregatesFilter<"Seat"> | number
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Seat"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Seat"> | Date | string
  seat_class_id?: Prisma.IntWithAggregatesFilter<"Seat"> | number
}

export type SeatCreateInput = {
  status: $Enums.SeatStatus
  created_at?: Date | string
  updated_at?: Date | string
  seat_class: Prisma.SeatClassCreateNestedOneWithoutSeatsInput
  ticket?: Prisma.TicketCreateNestedOneWithoutSeatInput
  trip: Prisma.TripCreateNestedOneWithoutSeatsInput
}

export type SeatUncheckedCreateInput = {
  id?: number
  status: $Enums.SeatStatus
  trip_id: number
  created_at?: Date | string
  updated_at?: Date | string
  seat_class_id: number
  ticket?: Prisma.TicketUncheckedCreateNestedOneWithoutSeatInput
}

export type SeatUpdateInput = {
  status?: Prisma.EnumSeatStatusFieldUpdateOperationsInput | $Enums.SeatStatus
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seat_class?: Prisma.SeatClassUpdateOneRequiredWithoutSeatsNestedInput
  ticket?: Prisma.TicketUpdateOneWithoutSeatNestedInput
  trip?: Prisma.TripUpdateOneRequiredWithoutSeatsNestedInput
}

export type SeatUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumSeatStatusFieldUpdateOperationsInput | $Enums.SeatStatus
  trip_id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seat_class_id?: Prisma.IntFieldUpdateOperationsInput | number
  ticket?: Prisma.TicketUncheckedUpdateOneWithoutSeatNestedInput
}

export type SeatCreateManyInput = {
  id?: number
  status: $Enums.SeatStatus
  trip_id: number
  created_at?: Date | string
  updated_at?: Date | string
  seat_class_id: number
}

export type SeatUpdateManyMutationInput = {
  status?: Prisma.EnumSeatStatusFieldUpdateOperationsInput | $Enums.SeatStatus
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SeatUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumSeatStatusFieldUpdateOperationsInput | $Enums.SeatStatus
  trip_id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seat_class_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SeatScalarRelationFilter = {
  is?: Prisma.SeatWhereInput
  isNot?: Prisma.SeatWhereInput
}

export type SeatCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  trip_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  seat_class_id?: Prisma.SortOrder
}

export type SeatAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  trip_id?: Prisma.SortOrder
  seat_class_id?: Prisma.SortOrder
}

export type SeatMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  trip_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  seat_class_id?: Prisma.SortOrder
}

export type SeatMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  trip_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  seat_class_id?: Prisma.SortOrder
}

export type SeatSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  trip_id?: Prisma.SortOrder
  seat_class_id?: Prisma.SortOrder
}

export type SeatListRelationFilter = {
  every?: Prisma.SeatWhereInput
  some?: Prisma.SeatWhereInput
  none?: Prisma.SeatWhereInput
}

export type SeatOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SeatCreateNestedOneWithoutTicketInput = {
  create?: Prisma.XOR<Prisma.SeatCreateWithoutTicketInput, Prisma.SeatUncheckedCreateWithoutTicketInput>
  connectOrCreate?: Prisma.SeatCreateOrConnectWithoutTicketInput
  connect?: Prisma.SeatWhereUniqueInput
}

export type SeatUpdateOneRequiredWithoutTicketNestedInput = {
  create?: Prisma.XOR<Prisma.SeatCreateWithoutTicketInput, Prisma.SeatUncheckedCreateWithoutTicketInput>
  connectOrCreate?: Prisma.SeatCreateOrConnectWithoutTicketInput
  upsert?: Prisma.SeatUpsertWithoutTicketInput
  connect?: Prisma.SeatWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SeatUpdateToOneWithWhereWithoutTicketInput, Prisma.SeatUpdateWithoutTicketInput>, Prisma.SeatUncheckedUpdateWithoutTicketInput>
}

export type EnumSeatStatusFieldUpdateOperationsInput = {
  set?: $Enums.SeatStatus
}

export type SeatCreateNestedManyWithoutSeat_classInput = {
  create?: Prisma.XOR<Prisma.SeatCreateWithoutSeat_classInput, Prisma.SeatUncheckedCreateWithoutSeat_classInput> | Prisma.SeatCreateWithoutSeat_classInput[] | Prisma.SeatUncheckedCreateWithoutSeat_classInput[]
  connectOrCreate?: Prisma.SeatCreateOrConnectWithoutSeat_classInput | Prisma.SeatCreateOrConnectWithoutSeat_classInput[]
  createMany?: Prisma.SeatCreateManySeat_classInputEnvelope
  connect?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
}

export type SeatUncheckedCreateNestedManyWithoutSeat_classInput = {
  create?: Prisma.XOR<Prisma.SeatCreateWithoutSeat_classInput, Prisma.SeatUncheckedCreateWithoutSeat_classInput> | Prisma.SeatCreateWithoutSeat_classInput[] | Prisma.SeatUncheckedCreateWithoutSeat_classInput[]
  connectOrCreate?: Prisma.SeatCreateOrConnectWithoutSeat_classInput | Prisma.SeatCreateOrConnectWithoutSeat_classInput[]
  createMany?: Prisma.SeatCreateManySeat_classInputEnvelope
  connect?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
}

export type SeatUpdateManyWithoutSeat_classNestedInput = {
  create?: Prisma.XOR<Prisma.SeatCreateWithoutSeat_classInput, Prisma.SeatUncheckedCreateWithoutSeat_classInput> | Prisma.SeatCreateWithoutSeat_classInput[] | Prisma.SeatUncheckedCreateWithoutSeat_classInput[]
  connectOrCreate?: Prisma.SeatCreateOrConnectWithoutSeat_classInput | Prisma.SeatCreateOrConnectWithoutSeat_classInput[]
  upsert?: Prisma.SeatUpsertWithWhereUniqueWithoutSeat_classInput | Prisma.SeatUpsertWithWhereUniqueWithoutSeat_classInput[]
  createMany?: Prisma.SeatCreateManySeat_classInputEnvelope
  set?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  disconnect?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  delete?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  connect?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  update?: Prisma.SeatUpdateWithWhereUniqueWithoutSeat_classInput | Prisma.SeatUpdateWithWhereUniqueWithoutSeat_classInput[]
  updateMany?: Prisma.SeatUpdateManyWithWhereWithoutSeat_classInput | Prisma.SeatUpdateManyWithWhereWithoutSeat_classInput[]
  deleteMany?: Prisma.SeatScalarWhereInput | Prisma.SeatScalarWhereInput[]
}

export type SeatUncheckedUpdateManyWithoutSeat_classNestedInput = {
  create?: Prisma.XOR<Prisma.SeatCreateWithoutSeat_classInput, Prisma.SeatUncheckedCreateWithoutSeat_classInput> | Prisma.SeatCreateWithoutSeat_classInput[] | Prisma.SeatUncheckedCreateWithoutSeat_classInput[]
  connectOrCreate?: Prisma.SeatCreateOrConnectWithoutSeat_classInput | Prisma.SeatCreateOrConnectWithoutSeat_classInput[]
  upsert?: Prisma.SeatUpsertWithWhereUniqueWithoutSeat_classInput | Prisma.SeatUpsertWithWhereUniqueWithoutSeat_classInput[]
  createMany?: Prisma.SeatCreateManySeat_classInputEnvelope
  set?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  disconnect?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  delete?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  connect?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  update?: Prisma.SeatUpdateWithWhereUniqueWithoutSeat_classInput | Prisma.SeatUpdateWithWhereUniqueWithoutSeat_classInput[]
  updateMany?: Prisma.SeatUpdateManyWithWhereWithoutSeat_classInput | Prisma.SeatUpdateManyWithWhereWithoutSeat_classInput[]
  deleteMany?: Prisma.SeatScalarWhereInput | Prisma.SeatScalarWhereInput[]
}

export type SeatCreateNestedManyWithoutTripInput = {
  create?: Prisma.XOR<Prisma.SeatCreateWithoutTripInput, Prisma.SeatUncheckedCreateWithoutTripInput> | Prisma.SeatCreateWithoutTripInput[] | Prisma.SeatUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.SeatCreateOrConnectWithoutTripInput | Prisma.SeatCreateOrConnectWithoutTripInput[]
  createMany?: Prisma.SeatCreateManyTripInputEnvelope
  connect?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
}

export type SeatUncheckedCreateNestedManyWithoutTripInput = {
  create?: Prisma.XOR<Prisma.SeatCreateWithoutTripInput, Prisma.SeatUncheckedCreateWithoutTripInput> | Prisma.SeatCreateWithoutTripInput[] | Prisma.SeatUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.SeatCreateOrConnectWithoutTripInput | Prisma.SeatCreateOrConnectWithoutTripInput[]
  createMany?: Prisma.SeatCreateManyTripInputEnvelope
  connect?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
}

export type SeatUpdateManyWithoutTripNestedInput = {
  create?: Prisma.XOR<Prisma.SeatCreateWithoutTripInput, Prisma.SeatUncheckedCreateWithoutTripInput> | Prisma.SeatCreateWithoutTripInput[] | Prisma.SeatUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.SeatCreateOrConnectWithoutTripInput | Prisma.SeatCreateOrConnectWithoutTripInput[]
  upsert?: Prisma.SeatUpsertWithWhereUniqueWithoutTripInput | Prisma.SeatUpsertWithWhereUniqueWithoutTripInput[]
  createMany?: Prisma.SeatCreateManyTripInputEnvelope
  set?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  disconnect?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  delete?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  connect?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  update?: Prisma.SeatUpdateWithWhereUniqueWithoutTripInput | Prisma.SeatUpdateWithWhereUniqueWithoutTripInput[]
  updateMany?: Prisma.SeatUpdateManyWithWhereWithoutTripInput | Prisma.SeatUpdateManyWithWhereWithoutTripInput[]
  deleteMany?: Prisma.SeatScalarWhereInput | Prisma.SeatScalarWhereInput[]
}

export type SeatUncheckedUpdateManyWithoutTripNestedInput = {
  create?: Prisma.XOR<Prisma.SeatCreateWithoutTripInput, Prisma.SeatUncheckedCreateWithoutTripInput> | Prisma.SeatCreateWithoutTripInput[] | Prisma.SeatUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.SeatCreateOrConnectWithoutTripInput | Prisma.SeatCreateOrConnectWithoutTripInput[]
  upsert?: Prisma.SeatUpsertWithWhereUniqueWithoutTripInput | Prisma.SeatUpsertWithWhereUniqueWithoutTripInput[]
  createMany?: Prisma.SeatCreateManyTripInputEnvelope
  set?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  disconnect?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  delete?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  connect?: Prisma.SeatWhereUniqueInput | Prisma.SeatWhereUniqueInput[]
  update?: Prisma.SeatUpdateWithWhereUniqueWithoutTripInput | Prisma.SeatUpdateWithWhereUniqueWithoutTripInput[]
  updateMany?: Prisma.SeatUpdateManyWithWhereWithoutTripInput | Prisma.SeatUpdateManyWithWhereWithoutTripInput[]
  deleteMany?: Prisma.SeatScalarWhereInput | Prisma.SeatScalarWhereInput[]
}

export type SeatCreateWithoutTicketInput = {
  status: $Enums.SeatStatus
  created_at?: Date | string
  updated_at?: Date | string
  seat_class: Prisma.SeatClassCreateNestedOneWithoutSeatsInput
  trip: Prisma.TripCreateNestedOneWithoutSeatsInput
}

export type SeatUncheckedCreateWithoutTicketInput = {
  id?: number
  status: $Enums.SeatStatus
  trip_id: number
  created_at?: Date | string
  updated_at?: Date | string
  seat_class_id: number
}

export type SeatCreateOrConnectWithoutTicketInput = {
  where: Prisma.SeatWhereUniqueInput
  create: Prisma.XOR<Prisma.SeatCreateWithoutTicketInput, Prisma.SeatUncheckedCreateWithoutTicketInput>
}

export type SeatUpsertWithoutTicketInput = {
  update: Prisma.XOR<Prisma.SeatUpdateWithoutTicketInput, Prisma.SeatUncheckedUpdateWithoutTicketInput>
  create: Prisma.XOR<Prisma.SeatCreateWithoutTicketInput, Prisma.SeatUncheckedCreateWithoutTicketInput>
  where?: Prisma.SeatWhereInput
}

export type SeatUpdateToOneWithWhereWithoutTicketInput = {
  where?: Prisma.SeatWhereInput
  data: Prisma.XOR<Prisma.SeatUpdateWithoutTicketInput, Prisma.SeatUncheckedUpdateWithoutTicketInput>
}

export type SeatUpdateWithoutTicketInput = {
  status?: Prisma.EnumSeatStatusFieldUpdateOperationsInput | $Enums.SeatStatus
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seat_class?: Prisma.SeatClassUpdateOneRequiredWithoutSeatsNestedInput
  trip?: Prisma.TripUpdateOneRequiredWithoutSeatsNestedInput
}

export type SeatUncheckedUpdateWithoutTicketInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumSeatStatusFieldUpdateOperationsInput | $Enums.SeatStatus
  trip_id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seat_class_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SeatCreateWithoutSeat_classInput = {
  status: $Enums.SeatStatus
  created_at?: Date | string
  updated_at?: Date | string
  ticket?: Prisma.TicketCreateNestedOneWithoutSeatInput
  trip: Prisma.TripCreateNestedOneWithoutSeatsInput
}

export type SeatUncheckedCreateWithoutSeat_classInput = {
  id?: number
  status: $Enums.SeatStatus
  trip_id: number
  created_at?: Date | string
  updated_at?: Date | string
  ticket?: Prisma.TicketUncheckedCreateNestedOneWithoutSeatInput
}

export type SeatCreateOrConnectWithoutSeat_classInput = {
  where: Prisma.SeatWhereUniqueInput
  create: Prisma.XOR<Prisma.SeatCreateWithoutSeat_classInput, Prisma.SeatUncheckedCreateWithoutSeat_classInput>
}

export type SeatCreateManySeat_classInputEnvelope = {
  data: Prisma.SeatCreateManySeat_classInput | Prisma.SeatCreateManySeat_classInput[]
  skipDuplicates?: boolean
}

export type SeatUpsertWithWhereUniqueWithoutSeat_classInput = {
  where: Prisma.SeatWhereUniqueInput
  update: Prisma.XOR<Prisma.SeatUpdateWithoutSeat_classInput, Prisma.SeatUncheckedUpdateWithoutSeat_classInput>
  create: Prisma.XOR<Prisma.SeatCreateWithoutSeat_classInput, Prisma.SeatUncheckedCreateWithoutSeat_classInput>
}

export type SeatUpdateWithWhereUniqueWithoutSeat_classInput = {
  where: Prisma.SeatWhereUniqueInput
  data: Prisma.XOR<Prisma.SeatUpdateWithoutSeat_classInput, Prisma.SeatUncheckedUpdateWithoutSeat_classInput>
}

export type SeatUpdateManyWithWhereWithoutSeat_classInput = {
  where: Prisma.SeatScalarWhereInput
  data: Prisma.XOR<Prisma.SeatUpdateManyMutationInput, Prisma.SeatUncheckedUpdateManyWithoutSeat_classInput>
}

export type SeatScalarWhereInput = {
  AND?: Prisma.SeatScalarWhereInput | Prisma.SeatScalarWhereInput[]
  OR?: Prisma.SeatScalarWhereInput[]
  NOT?: Prisma.SeatScalarWhereInput | Prisma.SeatScalarWhereInput[]
  id?: Prisma.IntFilter<"Seat"> | number
  status?: Prisma.EnumSeatStatusFilter<"Seat"> | $Enums.SeatStatus
  trip_id?: Prisma.IntFilter<"Seat"> | number
  created_at?: Prisma.DateTimeFilter<"Seat"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Seat"> | Date | string
  seat_class_id?: Prisma.IntFilter<"Seat"> | number
}

export type SeatCreateWithoutTripInput = {
  status: $Enums.SeatStatus
  created_at?: Date | string
  updated_at?: Date | string
  seat_class: Prisma.SeatClassCreateNestedOneWithoutSeatsInput
  ticket?: Prisma.TicketCreateNestedOneWithoutSeatInput
}

export type SeatUncheckedCreateWithoutTripInput = {
  id?: number
  status: $Enums.SeatStatus
  created_at?: Date | string
  updated_at?: Date | string
  seat_class_id: number
  ticket?: Prisma.TicketUncheckedCreateNestedOneWithoutSeatInput
}

export type SeatCreateOrConnectWithoutTripInput = {
  where: Prisma.SeatWhereUniqueInput
  create: Prisma.XOR<Prisma.SeatCreateWithoutTripInput, Prisma.SeatUncheckedCreateWithoutTripInput>
}

export type SeatCreateManyTripInputEnvelope = {
  data: Prisma.SeatCreateManyTripInput | Prisma.SeatCreateManyTripInput[]
  skipDuplicates?: boolean
}

export type SeatUpsertWithWhereUniqueWithoutTripInput = {
  where: Prisma.SeatWhereUniqueInput
  update: Prisma.XOR<Prisma.SeatUpdateWithoutTripInput, Prisma.SeatUncheckedUpdateWithoutTripInput>
  create: Prisma.XOR<Prisma.SeatCreateWithoutTripInput, Prisma.SeatUncheckedCreateWithoutTripInput>
}

export type SeatUpdateWithWhereUniqueWithoutTripInput = {
  where: Prisma.SeatWhereUniqueInput
  data: Prisma.XOR<Prisma.SeatUpdateWithoutTripInput, Prisma.SeatUncheckedUpdateWithoutTripInput>
}

export type SeatUpdateManyWithWhereWithoutTripInput = {
  where: Prisma.SeatScalarWhereInput
  data: Prisma.XOR<Prisma.SeatUpdateManyMutationInput, Prisma.SeatUncheckedUpdateManyWithoutTripInput>
}

export type SeatCreateManySeat_classInput = {
  id?: number
  status: $Enums.SeatStatus
  trip_id: number
  created_at?: Date | string
  updated_at?: Date | string
}

export type SeatUpdateWithoutSeat_classInput = {
  status?: Prisma.EnumSeatStatusFieldUpdateOperationsInput | $Enums.SeatStatus
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticket?: Prisma.TicketUpdateOneWithoutSeatNestedInput
  trip?: Prisma.TripUpdateOneRequiredWithoutSeatsNestedInput
}

export type SeatUncheckedUpdateWithoutSeat_classInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumSeatStatusFieldUpdateOperationsInput | $Enums.SeatStatus
  trip_id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticket?: Prisma.TicketUncheckedUpdateOneWithoutSeatNestedInput
}

export type SeatUncheckedUpdateManyWithoutSeat_classInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumSeatStatusFieldUpdateOperationsInput | $Enums.SeatStatus
  trip_id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SeatCreateManyTripInput = {
  id?: number
  status: $Enums.SeatStatus
  created_at?: Date | string
  updated_at?: Date | string
  seat_class_id: number
}

export type SeatUpdateWithoutTripInput = {
  status?: Prisma.EnumSeatStatusFieldUpdateOperationsInput | $Enums.SeatStatus
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seat_class?: Prisma.SeatClassUpdateOneRequiredWithoutSeatsNestedInput
  ticket?: Prisma.TicketUpdateOneWithoutSeatNestedInput
}

export type SeatUncheckedUpdateWithoutTripInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumSeatStatusFieldUpdateOperationsInput | $Enums.SeatStatus
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seat_class_id?: Prisma.IntFieldUpdateOperationsInput | number
  ticket?: Prisma.TicketUncheckedUpdateOneWithoutSeatNestedInput
}

export type SeatUncheckedUpdateManyWithoutTripInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumSeatStatusFieldUpdateOperationsInput | $Enums.SeatStatus
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  seat_class_id?: Prisma.IntFieldUpdateOperationsInput | number
}



export type SeatSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  trip_id?: boolean
  created_at?: boolean
  updated_at?: boolean
  seat_class_id?: boolean
  seat_class?: boolean | Prisma.SeatClassDefaultArgs<ExtArgs>
  ticket?: boolean | Prisma.Seat$ticketArgs<ExtArgs>
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}, ExtArgs["result"]["seat"]>

export type SeatSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  trip_id?: boolean
  created_at?: boolean
  updated_at?: boolean
  seat_class_id?: boolean
  seat_class?: boolean | Prisma.SeatClassDefaultArgs<ExtArgs>
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}, ExtArgs["result"]["seat"]>

export type SeatSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  trip_id?: boolean
  created_at?: boolean
  updated_at?: boolean
  seat_class_id?: boolean
  seat_class?: boolean | Prisma.SeatClassDefaultArgs<ExtArgs>
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}, ExtArgs["result"]["seat"]>

export type SeatSelectScalar = {
  id?: boolean
  status?: boolean
  trip_id?: boolean
  created_at?: boolean
  updated_at?: boolean
  seat_class_id?: boolean
}

export type SeatOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "status" | "trip_id" | "created_at" | "updated_at" | "seat_class_id", ExtArgs["result"]["seat"]>
export type SeatInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  seat_class?: boolean | Prisma.SeatClassDefaultArgs<ExtArgs>
  ticket?: boolean | Prisma.Seat$ticketArgs<ExtArgs>
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}
export type SeatIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  seat_class?: boolean | Prisma.SeatClassDefaultArgs<ExtArgs>
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}
export type SeatIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  seat_class?: boolean | Prisma.SeatClassDefaultArgs<ExtArgs>
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}

export type $SeatPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Seat"
  objects: {
    seat_class: Prisma.$SeatClassPayload<ExtArgs>
    ticket: Prisma.$TicketPayload<ExtArgs> | null
    trip: Prisma.$TripPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    status: $Enums.SeatStatus
    trip_id: number
    created_at: Date
    updated_at: Date
    seat_class_id: number
  }, ExtArgs["result"]["seat"]>
  composites: {}
}

export type SeatGetPayload<S extends boolean | null | undefined | SeatDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SeatPayload, S>

export type SeatCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SeatFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SeatCountAggregateInputType | true
  }

export interface SeatDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Seat'], meta: { name: 'Seat' } }
  /**
   * Find zero or one Seat that matches the filter.
   * @param {SeatFindUniqueArgs} args - Arguments to find a Seat
   * @example
   * // Get one Seat
   * const seat = await prisma.seat.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SeatFindUniqueArgs>(args: Prisma.SelectSubset<T, SeatFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SeatClient<runtime.Types.Result.GetResult<Prisma.$SeatPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Seat that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SeatFindUniqueOrThrowArgs} args - Arguments to find a Seat
   * @example
   * // Get one Seat
   * const seat = await prisma.seat.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SeatFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SeatFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SeatClient<runtime.Types.Result.GetResult<Prisma.$SeatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Seat that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatFindFirstArgs} args - Arguments to find a Seat
   * @example
   * // Get one Seat
   * const seat = await prisma.seat.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SeatFindFirstArgs>(args?: Prisma.SelectSubset<T, SeatFindFirstArgs<ExtArgs>>): Prisma.Prisma__SeatClient<runtime.Types.Result.GetResult<Prisma.$SeatPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Seat that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatFindFirstOrThrowArgs} args - Arguments to find a Seat
   * @example
   * // Get one Seat
   * const seat = await prisma.seat.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SeatFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SeatFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SeatClient<runtime.Types.Result.GetResult<Prisma.$SeatPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Seats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Seats
   * const seats = await prisma.seat.findMany()
   * 
   * // Get first 10 Seats
   * const seats = await prisma.seat.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const seatWithIdOnly = await prisma.seat.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SeatFindManyArgs>(args?: Prisma.SelectSubset<T, SeatFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Seat.
   * @param {SeatCreateArgs} args - Arguments to create a Seat.
   * @example
   * // Create one Seat
   * const Seat = await prisma.seat.create({
   *   data: {
   *     // ... data to create a Seat
   *   }
   * })
   * 
   */
  create<T extends SeatCreateArgs>(args: Prisma.SelectSubset<T, SeatCreateArgs<ExtArgs>>): Prisma.Prisma__SeatClient<runtime.Types.Result.GetResult<Prisma.$SeatPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Seats.
   * @param {SeatCreateManyArgs} args - Arguments to create many Seats.
   * @example
   * // Create many Seats
   * const seat = await prisma.seat.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SeatCreateManyArgs>(args?: Prisma.SelectSubset<T, SeatCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Seats and returns the data saved in the database.
   * @param {SeatCreateManyAndReturnArgs} args - Arguments to create many Seats.
   * @example
   * // Create many Seats
   * const seat = await prisma.seat.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Seats and only return the `id`
   * const seatWithIdOnly = await prisma.seat.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SeatCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SeatCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeatPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Seat.
   * @param {SeatDeleteArgs} args - Arguments to delete one Seat.
   * @example
   * // Delete one Seat
   * const Seat = await prisma.seat.delete({
   *   where: {
   *     // ... filter to delete one Seat
   *   }
   * })
   * 
   */
  delete<T extends SeatDeleteArgs>(args: Prisma.SelectSubset<T, SeatDeleteArgs<ExtArgs>>): Prisma.Prisma__SeatClient<runtime.Types.Result.GetResult<Prisma.$SeatPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Seat.
   * @param {SeatUpdateArgs} args - Arguments to update one Seat.
   * @example
   * // Update one Seat
   * const seat = await prisma.seat.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SeatUpdateArgs>(args: Prisma.SelectSubset<T, SeatUpdateArgs<ExtArgs>>): Prisma.Prisma__SeatClient<runtime.Types.Result.GetResult<Prisma.$SeatPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Seats.
   * @param {SeatDeleteManyArgs} args - Arguments to filter Seats to delete.
   * @example
   * // Delete a few Seats
   * const { count } = await prisma.seat.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SeatDeleteManyArgs>(args?: Prisma.SelectSubset<T, SeatDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Seats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Seats
   * const seat = await prisma.seat.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SeatUpdateManyArgs>(args: Prisma.SelectSubset<T, SeatUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Seats and returns the data updated in the database.
   * @param {SeatUpdateManyAndReturnArgs} args - Arguments to update many Seats.
   * @example
   * // Update many Seats
   * const seat = await prisma.seat.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Seats and only return the `id`
   * const seatWithIdOnly = await prisma.seat.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SeatUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SeatUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeatPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Seat.
   * @param {SeatUpsertArgs} args - Arguments to update or create a Seat.
   * @example
   * // Update or create a Seat
   * const seat = await prisma.seat.upsert({
   *   create: {
   *     // ... data to create a Seat
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Seat we want to update
   *   }
   * })
   */
  upsert<T extends SeatUpsertArgs>(args: Prisma.SelectSubset<T, SeatUpsertArgs<ExtArgs>>): Prisma.Prisma__SeatClient<runtime.Types.Result.GetResult<Prisma.$SeatPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Seats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatCountArgs} args - Arguments to filter Seats to count.
   * @example
   * // Count the number of Seats
   * const count = await prisma.seat.count({
   *   where: {
   *     // ... the filter for the Seats we want to count
   *   }
   * })
  **/
  count<T extends SeatCountArgs>(
    args?: Prisma.Subset<T, SeatCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SeatCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Seat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SeatAggregateArgs>(args: Prisma.Subset<T, SeatAggregateArgs>): Prisma.PrismaPromise<GetSeatAggregateType<T>>

  /**
   * Group by Seat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SeatGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SeatGroupByArgs['orderBy'] }
      : { orderBy?: SeatGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SeatGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSeatGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Seat model
 */
readonly fields: SeatFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Seat.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SeatClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  seat_class<T extends Prisma.SeatClassDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SeatClassDefaultArgs<ExtArgs>>): Prisma.Prisma__SeatClassClient<runtime.Types.Result.GetResult<Prisma.$SeatClassPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  ticket<T extends Prisma.Seat$ticketArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Seat$ticketArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  trip<T extends Prisma.TripDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TripDefaultArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Seat model
 */
export interface SeatFieldRefs {
  readonly id: Prisma.FieldRef<"Seat", 'Int'>
  readonly status: Prisma.FieldRef<"Seat", 'SeatStatus'>
  readonly trip_id: Prisma.FieldRef<"Seat", 'Int'>
  readonly created_at: Prisma.FieldRef<"Seat", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Seat", 'DateTime'>
  readonly seat_class_id: Prisma.FieldRef<"Seat", 'Int'>
}
    

// Custom InputTypes
/**
 * Seat findUnique
 */
export type SeatFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seat
   */
  select?: Prisma.SeatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seat
   */
  omit?: Prisma.SeatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatInclude<ExtArgs> | null
  /**
   * Filter, which Seat to fetch.
   */
  where: Prisma.SeatWhereUniqueInput
}

/**
 * Seat findUniqueOrThrow
 */
export type SeatFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seat
   */
  select?: Prisma.SeatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seat
   */
  omit?: Prisma.SeatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatInclude<ExtArgs> | null
  /**
   * Filter, which Seat to fetch.
   */
  where: Prisma.SeatWhereUniqueInput
}

/**
 * Seat findFirst
 */
export type SeatFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seat
   */
  select?: Prisma.SeatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seat
   */
  omit?: Prisma.SeatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatInclude<ExtArgs> | null
  /**
   * Filter, which Seat to fetch.
   */
  where?: Prisma.SeatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seats to fetch.
   */
  orderBy?: Prisma.SeatOrderByWithRelationInput | Prisma.SeatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Seats.
   */
  cursor?: Prisma.SeatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Seats.
   */
  distinct?: Prisma.SeatScalarFieldEnum | Prisma.SeatScalarFieldEnum[]
}

/**
 * Seat findFirstOrThrow
 */
export type SeatFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seat
   */
  select?: Prisma.SeatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seat
   */
  omit?: Prisma.SeatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatInclude<ExtArgs> | null
  /**
   * Filter, which Seat to fetch.
   */
  where?: Prisma.SeatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seats to fetch.
   */
  orderBy?: Prisma.SeatOrderByWithRelationInput | Prisma.SeatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Seats.
   */
  cursor?: Prisma.SeatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Seats.
   */
  distinct?: Prisma.SeatScalarFieldEnum | Prisma.SeatScalarFieldEnum[]
}

/**
 * Seat findMany
 */
export type SeatFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seat
   */
  select?: Prisma.SeatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seat
   */
  omit?: Prisma.SeatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatInclude<ExtArgs> | null
  /**
   * Filter, which Seats to fetch.
   */
  where?: Prisma.SeatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seats to fetch.
   */
  orderBy?: Prisma.SeatOrderByWithRelationInput | Prisma.SeatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Seats.
   */
  cursor?: Prisma.SeatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Seats.
   */
  distinct?: Prisma.SeatScalarFieldEnum | Prisma.SeatScalarFieldEnum[]
}

/**
 * Seat create
 */
export type SeatCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seat
   */
  select?: Prisma.SeatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seat
   */
  omit?: Prisma.SeatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatInclude<ExtArgs> | null
  /**
   * The data needed to create a Seat.
   */
  data: Prisma.XOR<Prisma.SeatCreateInput, Prisma.SeatUncheckedCreateInput>
}

/**
 * Seat createMany
 */
export type SeatCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Seats.
   */
  data: Prisma.SeatCreateManyInput | Prisma.SeatCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Seat createManyAndReturn
 */
export type SeatCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seat
   */
  select?: Prisma.SeatSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Seat
   */
  omit?: Prisma.SeatOmit<ExtArgs> | null
  /**
   * The data used to create many Seats.
   */
  data: Prisma.SeatCreateManyInput | Prisma.SeatCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Seat update
 */
export type SeatUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seat
   */
  select?: Prisma.SeatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seat
   */
  omit?: Prisma.SeatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatInclude<ExtArgs> | null
  /**
   * The data needed to update a Seat.
   */
  data: Prisma.XOR<Prisma.SeatUpdateInput, Prisma.SeatUncheckedUpdateInput>
  /**
   * Choose, which Seat to update.
   */
  where: Prisma.SeatWhereUniqueInput
}

/**
 * Seat updateMany
 */
export type SeatUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Seats.
   */
  data: Prisma.XOR<Prisma.SeatUpdateManyMutationInput, Prisma.SeatUncheckedUpdateManyInput>
  /**
   * Filter which Seats to update
   */
  where?: Prisma.SeatWhereInput
  /**
   * Limit how many Seats to update.
   */
  limit?: number
}

/**
 * Seat updateManyAndReturn
 */
export type SeatUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seat
   */
  select?: Prisma.SeatSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Seat
   */
  omit?: Prisma.SeatOmit<ExtArgs> | null
  /**
   * The data used to update Seats.
   */
  data: Prisma.XOR<Prisma.SeatUpdateManyMutationInput, Prisma.SeatUncheckedUpdateManyInput>
  /**
   * Filter which Seats to update
   */
  where?: Prisma.SeatWhereInput
  /**
   * Limit how many Seats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Seat upsert
 */
export type SeatUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seat
   */
  select?: Prisma.SeatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seat
   */
  omit?: Prisma.SeatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatInclude<ExtArgs> | null
  /**
   * The filter to search for the Seat to update in case it exists.
   */
  where: Prisma.SeatWhereUniqueInput
  /**
   * In case the Seat found by the `where` argument doesn't exist, create a new Seat with this data.
   */
  create: Prisma.XOR<Prisma.SeatCreateInput, Prisma.SeatUncheckedCreateInput>
  /**
   * In case the Seat was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SeatUpdateInput, Prisma.SeatUncheckedUpdateInput>
}

/**
 * Seat delete
 */
export type SeatDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seat
   */
  select?: Prisma.SeatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seat
   */
  omit?: Prisma.SeatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatInclude<ExtArgs> | null
  /**
   * Filter which Seat to delete.
   */
  where: Prisma.SeatWhereUniqueInput
}

/**
 * Seat deleteMany
 */
export type SeatDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Seats to delete
   */
  where?: Prisma.SeatWhereInput
  /**
   * Limit how many Seats to delete.
   */
  limit?: number
}

/**
 * Seat.ticket
 */
export type Seat$ticketArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  where?: Prisma.TicketWhereInput
}

/**
 * Seat without action
 */
export type SeatDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seat
   */
  select?: Prisma.SeatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seat
   */
  omit?: Prisma.SeatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatInclude<ExtArgs> | null
}
