
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SeatClass` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SeatClass
 * 
 */
export type SeatClassModel = runtime.Types.Result.DefaultSelection<Prisma.$SeatClassPayload>

export type AggregateSeatClass = {
  _count: SeatClassCountAggregateOutputType | null
  _avg: SeatClassAvgAggregateOutputType | null
  _sum: SeatClassSumAggregateOutputType | null
  _min: SeatClassMinAggregateOutputType | null
  _max: SeatClassMaxAggregateOutputType | null
}

export type SeatClassAvgAggregateOutputType = {
  id: number | null
  price: number | null
}

export type SeatClassSumAggregateOutputType = {
  id: number | null
  price: number | null
}

export type SeatClassMinAggregateOutputType = {
  id: number | null
  name: string | null
  price: number | null
}

export type SeatClassMaxAggregateOutputType = {
  id: number | null
  name: string | null
  price: number | null
}

export type SeatClassCountAggregateOutputType = {
  id: number
  name: number
  price: number
  _all: number
}


export type SeatClassAvgAggregateInputType = {
  id?: true
  price?: true
}

export type SeatClassSumAggregateInputType = {
  id?: true
  price?: true
}

export type SeatClassMinAggregateInputType = {
  id?: true
  name?: true
  price?: true
}

export type SeatClassMaxAggregateInputType = {
  id?: true
  name?: true
  price?: true
}

export type SeatClassCountAggregateInputType = {
  id?: true
  name?: true
  price?: true
  _all?: true
}

export type SeatClassAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SeatClass to aggregate.
   */
  where?: Prisma.SeatClassWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SeatClasses to fetch.
   */
  orderBy?: Prisma.SeatClassOrderByWithRelationInput | Prisma.SeatClassOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SeatClassWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SeatClasses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SeatClasses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SeatClasses
  **/
  _count?: true | SeatClassCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SeatClassAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SeatClassSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SeatClassMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SeatClassMaxAggregateInputType
}

export type GetSeatClassAggregateType<T extends SeatClassAggregateArgs> = {
      [P in keyof T & keyof AggregateSeatClass]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSeatClass[P]>
    : Prisma.GetScalarType<T[P], AggregateSeatClass[P]>
}




export type SeatClassGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SeatClassWhereInput
  orderBy?: Prisma.SeatClassOrderByWithAggregationInput | Prisma.SeatClassOrderByWithAggregationInput[]
  by: Prisma.SeatClassScalarFieldEnum[] | Prisma.SeatClassScalarFieldEnum
  having?: Prisma.SeatClassScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SeatClassCountAggregateInputType | true
  _avg?: SeatClassAvgAggregateInputType
  _sum?: SeatClassSumAggregateInputType
  _min?: SeatClassMinAggregateInputType
  _max?: SeatClassMaxAggregateInputType
}

export type SeatClassGroupByOutputType = {
  id: number
  name: string
  price: number
  _count: SeatClassCountAggregateOutputType | null
  _avg: SeatClassAvgAggregateOutputType | null
  _sum: SeatClassSumAggregateOutputType | null
  _min: SeatClassMinAggregateOutputType | null
  _max: SeatClassMaxAggregateOutputType | null
}

export type GetSeatClassGroupByPayload<T extends SeatClassGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SeatClassGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SeatClassGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SeatClassGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SeatClassGroupByOutputType[P]>
      }
    >
  >



export type SeatClassWhereInput = {
  AND?: Prisma.SeatClassWhereInput | Prisma.SeatClassWhereInput[]
  OR?: Prisma.SeatClassWhereInput[]
  NOT?: Prisma.SeatClassWhereInput | Prisma.SeatClassWhereInput[]
  id?: Prisma.IntFilter<"SeatClass"> | number
  name?: Prisma.StringFilter<"SeatClass"> | string
  price?: Prisma.FloatFilter<"SeatClass"> | number
  seats?: Prisma.SeatListRelationFilter
}

export type SeatClassOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  seats?: Prisma.SeatOrderByRelationAggregateInput
}

export type SeatClassWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.SeatClassWhereInput | Prisma.SeatClassWhereInput[]
  OR?: Prisma.SeatClassWhereInput[]
  NOT?: Prisma.SeatClassWhereInput | Prisma.SeatClassWhereInput[]
  name?: Prisma.StringFilter<"SeatClass"> | string
  price?: Prisma.FloatFilter<"SeatClass"> | number
  seats?: Prisma.SeatListRelationFilter
}, "id">

export type SeatClassOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  _count?: Prisma.SeatClassCountOrderByAggregateInput
  _avg?: Prisma.SeatClassAvgOrderByAggregateInput
  _max?: Prisma.SeatClassMaxOrderByAggregateInput
  _min?: Prisma.SeatClassMinOrderByAggregateInput
  _sum?: Prisma.SeatClassSumOrderByAggregateInput
}

export type SeatClassScalarWhereWithAggregatesInput = {
  AND?: Prisma.SeatClassScalarWhereWithAggregatesInput | Prisma.SeatClassScalarWhereWithAggregatesInput[]
  OR?: Prisma.SeatClassScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SeatClassScalarWhereWithAggregatesInput | Prisma.SeatClassScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"SeatClass"> | number
  name?: Prisma.StringWithAggregatesFilter<"SeatClass"> | string
  price?: Prisma.FloatWithAggregatesFilter<"SeatClass"> | number
}

export type SeatClassCreateInput = {
  name: string
  price: number
  seats?: Prisma.SeatCreateNestedManyWithoutSeat_classInput
}

export type SeatClassUncheckedCreateInput = {
  id?: number
  name: string
  price: number
  seats?: Prisma.SeatUncheckedCreateNestedManyWithoutSeat_classInput
}

export type SeatClassUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  seats?: Prisma.SeatUpdateManyWithoutSeat_classNestedInput
}

export type SeatClassUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  seats?: Prisma.SeatUncheckedUpdateManyWithoutSeat_classNestedInput
}

export type SeatClassCreateManyInput = {
  id?: number
  name: string
  price: number
}

export type SeatClassUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type SeatClassUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type SeatClassScalarRelationFilter = {
  is?: Prisma.SeatClassWhereInput
  isNot?: Prisma.SeatClassWhereInput
}

export type SeatClassCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type SeatClassAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type SeatClassMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type SeatClassMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type SeatClassSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type SeatClassCreateNestedOneWithoutSeatsInput = {
  create?: Prisma.XOR<Prisma.SeatClassCreateWithoutSeatsInput, Prisma.SeatClassUncheckedCreateWithoutSeatsInput>
  connectOrCreate?: Prisma.SeatClassCreateOrConnectWithoutSeatsInput
  connect?: Prisma.SeatClassWhereUniqueInput
}

export type SeatClassUpdateOneRequiredWithoutSeatsNestedInput = {
  create?: Prisma.XOR<Prisma.SeatClassCreateWithoutSeatsInput, Prisma.SeatClassUncheckedCreateWithoutSeatsInput>
  connectOrCreate?: Prisma.SeatClassCreateOrConnectWithoutSeatsInput
  upsert?: Prisma.SeatClassUpsertWithoutSeatsInput
  connect?: Prisma.SeatClassWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SeatClassUpdateToOneWithWhereWithoutSeatsInput, Prisma.SeatClassUpdateWithoutSeatsInput>, Prisma.SeatClassUncheckedUpdateWithoutSeatsInput>
}

export type SeatClassCreateWithoutSeatsInput = {
  name: string
  price: number
}

export type SeatClassUncheckedCreateWithoutSeatsInput = {
  id?: number
  name: string
  price: number
}

export type SeatClassCreateOrConnectWithoutSeatsInput = {
  where: Prisma.SeatClassWhereUniqueInput
  create: Prisma.XOR<Prisma.SeatClassCreateWithoutSeatsInput, Prisma.SeatClassUncheckedCreateWithoutSeatsInput>
}

export type SeatClassUpsertWithoutSeatsInput = {
  update: Prisma.XOR<Prisma.SeatClassUpdateWithoutSeatsInput, Prisma.SeatClassUncheckedUpdateWithoutSeatsInput>
  create: Prisma.XOR<Prisma.SeatClassCreateWithoutSeatsInput, Prisma.SeatClassUncheckedCreateWithoutSeatsInput>
  where?: Prisma.SeatClassWhereInput
}

export type SeatClassUpdateToOneWithWhereWithoutSeatsInput = {
  where?: Prisma.SeatClassWhereInput
  data: Prisma.XOR<Prisma.SeatClassUpdateWithoutSeatsInput, Prisma.SeatClassUncheckedUpdateWithoutSeatsInput>
}

export type SeatClassUpdateWithoutSeatsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type SeatClassUncheckedUpdateWithoutSeatsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
}


/**
 * Count Type SeatClassCountOutputType
 */

export type SeatClassCountOutputType = {
  seats: number
}

export type SeatClassCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  seats?: boolean | SeatClassCountOutputTypeCountSeatsArgs
}

/**
 * SeatClassCountOutputType without action
 */
export type SeatClassCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatClassCountOutputType
   */
  select?: Prisma.SeatClassCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SeatClassCountOutputType without action
 */
export type SeatClassCountOutputTypeCountSeatsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SeatWhereInput
}


export type SeatClassSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  price?: boolean
  seats?: boolean | Prisma.SeatClass$seatsArgs<ExtArgs>
  _count?: boolean | Prisma.SeatClassCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["seatClass"]>

export type SeatClassSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  price?: boolean
}, ExtArgs["result"]["seatClass"]>

export type SeatClassSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  price?: boolean
}, ExtArgs["result"]["seatClass"]>

export type SeatClassSelectScalar = {
  id?: boolean
  name?: boolean
  price?: boolean
}

export type SeatClassOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "price", ExtArgs["result"]["seatClass"]>
export type SeatClassInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  seats?: boolean | Prisma.SeatClass$seatsArgs<ExtArgs>
  _count?: boolean | Prisma.SeatClassCountOutputTypeDefaultArgs<ExtArgs>
}
export type SeatClassIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type SeatClassIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $SeatClassPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SeatClass"
  objects: {
    seats: Prisma.$SeatPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    price: number
  }, ExtArgs["result"]["seatClass"]>
  composites: {}
}

export type SeatClassGetPayload<S extends boolean | null | undefined | SeatClassDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SeatClassPayload, S>

export type SeatClassCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SeatClassFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SeatClassCountAggregateInputType | true
  }

export interface SeatClassDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SeatClass'], meta: { name: 'SeatClass' } }
  /**
   * Find zero or one SeatClass that matches the filter.
   * @param {SeatClassFindUniqueArgs} args - Arguments to find a SeatClass
   * @example
   * // Get one SeatClass
   * const seatClass = await prisma.seatClass.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SeatClassFindUniqueArgs>(args: Prisma.SelectSubset<T, SeatClassFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SeatClassClient<runtime.Types.Result.GetResult<Prisma.$SeatClassPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SeatClass that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SeatClassFindUniqueOrThrowArgs} args - Arguments to find a SeatClass
   * @example
   * // Get one SeatClass
   * const seatClass = await prisma.seatClass.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SeatClassFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SeatClassFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SeatClassClient<runtime.Types.Result.GetResult<Prisma.$SeatClassPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SeatClass that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatClassFindFirstArgs} args - Arguments to find a SeatClass
   * @example
   * // Get one SeatClass
   * const seatClass = await prisma.seatClass.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SeatClassFindFirstArgs>(args?: Prisma.SelectSubset<T, SeatClassFindFirstArgs<ExtArgs>>): Prisma.Prisma__SeatClassClient<runtime.Types.Result.GetResult<Prisma.$SeatClassPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SeatClass that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatClassFindFirstOrThrowArgs} args - Arguments to find a SeatClass
   * @example
   * // Get one SeatClass
   * const seatClass = await prisma.seatClass.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SeatClassFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SeatClassFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SeatClassClient<runtime.Types.Result.GetResult<Prisma.$SeatClassPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SeatClasses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatClassFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SeatClasses
   * const seatClasses = await prisma.seatClass.findMany()
   * 
   * // Get first 10 SeatClasses
   * const seatClasses = await prisma.seatClass.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const seatClassWithIdOnly = await prisma.seatClass.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SeatClassFindManyArgs>(args?: Prisma.SelectSubset<T, SeatClassFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeatClassPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SeatClass.
   * @param {SeatClassCreateArgs} args - Arguments to create a SeatClass.
   * @example
   * // Create one SeatClass
   * const SeatClass = await prisma.seatClass.create({
   *   data: {
   *     // ... data to create a SeatClass
   *   }
   * })
   * 
   */
  create<T extends SeatClassCreateArgs>(args: Prisma.SelectSubset<T, SeatClassCreateArgs<ExtArgs>>): Prisma.Prisma__SeatClassClient<runtime.Types.Result.GetResult<Prisma.$SeatClassPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SeatClasses.
   * @param {SeatClassCreateManyArgs} args - Arguments to create many SeatClasses.
   * @example
   * // Create many SeatClasses
   * const seatClass = await prisma.seatClass.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SeatClassCreateManyArgs>(args?: Prisma.SelectSubset<T, SeatClassCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SeatClasses and returns the data saved in the database.
   * @param {SeatClassCreateManyAndReturnArgs} args - Arguments to create many SeatClasses.
   * @example
   * // Create many SeatClasses
   * const seatClass = await prisma.seatClass.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SeatClasses and only return the `id`
   * const seatClassWithIdOnly = await prisma.seatClass.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SeatClassCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SeatClassCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeatClassPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SeatClass.
   * @param {SeatClassDeleteArgs} args - Arguments to delete one SeatClass.
   * @example
   * // Delete one SeatClass
   * const SeatClass = await prisma.seatClass.delete({
   *   where: {
   *     // ... filter to delete one SeatClass
   *   }
   * })
   * 
   */
  delete<T extends SeatClassDeleteArgs>(args: Prisma.SelectSubset<T, SeatClassDeleteArgs<ExtArgs>>): Prisma.Prisma__SeatClassClient<runtime.Types.Result.GetResult<Prisma.$SeatClassPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SeatClass.
   * @param {SeatClassUpdateArgs} args - Arguments to update one SeatClass.
   * @example
   * // Update one SeatClass
   * const seatClass = await prisma.seatClass.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SeatClassUpdateArgs>(args: Prisma.SelectSubset<T, SeatClassUpdateArgs<ExtArgs>>): Prisma.Prisma__SeatClassClient<runtime.Types.Result.GetResult<Prisma.$SeatClassPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SeatClasses.
   * @param {SeatClassDeleteManyArgs} args - Arguments to filter SeatClasses to delete.
   * @example
   * // Delete a few SeatClasses
   * const { count } = await prisma.seatClass.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SeatClassDeleteManyArgs>(args?: Prisma.SelectSubset<T, SeatClassDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SeatClasses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatClassUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SeatClasses
   * const seatClass = await prisma.seatClass.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SeatClassUpdateManyArgs>(args: Prisma.SelectSubset<T, SeatClassUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SeatClasses and returns the data updated in the database.
   * @param {SeatClassUpdateManyAndReturnArgs} args - Arguments to update many SeatClasses.
   * @example
   * // Update many SeatClasses
   * const seatClass = await prisma.seatClass.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SeatClasses and only return the `id`
   * const seatClassWithIdOnly = await prisma.seatClass.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SeatClassUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SeatClassUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeatClassPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SeatClass.
   * @param {SeatClassUpsertArgs} args - Arguments to update or create a SeatClass.
   * @example
   * // Update or create a SeatClass
   * const seatClass = await prisma.seatClass.upsert({
   *   create: {
   *     // ... data to create a SeatClass
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SeatClass we want to update
   *   }
   * })
   */
  upsert<T extends SeatClassUpsertArgs>(args: Prisma.SelectSubset<T, SeatClassUpsertArgs<ExtArgs>>): Prisma.Prisma__SeatClassClient<runtime.Types.Result.GetResult<Prisma.$SeatClassPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SeatClasses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatClassCountArgs} args - Arguments to filter SeatClasses to count.
   * @example
   * // Count the number of SeatClasses
   * const count = await prisma.seatClass.count({
   *   where: {
   *     // ... the filter for the SeatClasses we want to count
   *   }
   * })
  **/
  count<T extends SeatClassCountArgs>(
    args?: Prisma.Subset<T, SeatClassCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SeatClassCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SeatClass.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatClassAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SeatClassAggregateArgs>(args: Prisma.Subset<T, SeatClassAggregateArgs>): Prisma.PrismaPromise<GetSeatClassAggregateType<T>>

  /**
   * Group by SeatClass.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatClassGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SeatClassGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SeatClassGroupByArgs['orderBy'] }
      : { orderBy?: SeatClassGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SeatClassGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSeatClassGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SeatClass model
 */
readonly fields: SeatClassFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SeatClass.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SeatClassClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  seats<T extends Prisma.SeatClass$seatsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SeatClass$seatsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SeatClass model
 */
export interface SeatClassFieldRefs {
  readonly id: Prisma.FieldRef<"SeatClass", 'Int'>
  readonly name: Prisma.FieldRef<"SeatClass", 'String'>
  readonly price: Prisma.FieldRef<"SeatClass", 'Float'>
}
    

// Custom InputTypes
/**
 * SeatClass findUnique
 */
export type SeatClassFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatClass
   */
  select?: Prisma.SeatClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatClass
   */
  omit?: Prisma.SeatClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatClassInclude<ExtArgs> | null
  /**
   * Filter, which SeatClass to fetch.
   */
  where: Prisma.SeatClassWhereUniqueInput
}

/**
 * SeatClass findUniqueOrThrow
 */
export type SeatClassFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatClass
   */
  select?: Prisma.SeatClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatClass
   */
  omit?: Prisma.SeatClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatClassInclude<ExtArgs> | null
  /**
   * Filter, which SeatClass to fetch.
   */
  where: Prisma.SeatClassWhereUniqueInput
}

/**
 * SeatClass findFirst
 */
export type SeatClassFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatClass
   */
  select?: Prisma.SeatClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatClass
   */
  omit?: Prisma.SeatClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatClassInclude<ExtArgs> | null
  /**
   * Filter, which SeatClass to fetch.
   */
  where?: Prisma.SeatClassWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SeatClasses to fetch.
   */
  orderBy?: Prisma.SeatClassOrderByWithRelationInput | Prisma.SeatClassOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SeatClasses.
   */
  cursor?: Prisma.SeatClassWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SeatClasses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SeatClasses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SeatClasses.
   */
  distinct?: Prisma.SeatClassScalarFieldEnum | Prisma.SeatClassScalarFieldEnum[]
}

/**
 * SeatClass findFirstOrThrow
 */
export type SeatClassFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatClass
   */
  select?: Prisma.SeatClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatClass
   */
  omit?: Prisma.SeatClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatClassInclude<ExtArgs> | null
  /**
   * Filter, which SeatClass to fetch.
   */
  where?: Prisma.SeatClassWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SeatClasses to fetch.
   */
  orderBy?: Prisma.SeatClassOrderByWithRelationInput | Prisma.SeatClassOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SeatClasses.
   */
  cursor?: Prisma.SeatClassWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SeatClasses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SeatClasses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SeatClasses.
   */
  distinct?: Prisma.SeatClassScalarFieldEnum | Prisma.SeatClassScalarFieldEnum[]
}

/**
 * SeatClass findMany
 */
export type SeatClassFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatClass
   */
  select?: Prisma.SeatClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatClass
   */
  omit?: Prisma.SeatClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatClassInclude<ExtArgs> | null
  /**
   * Filter, which SeatClasses to fetch.
   */
  where?: Prisma.SeatClassWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SeatClasses to fetch.
   */
  orderBy?: Prisma.SeatClassOrderByWithRelationInput | Prisma.SeatClassOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SeatClasses.
   */
  cursor?: Prisma.SeatClassWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SeatClasses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SeatClasses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SeatClasses.
   */
  distinct?: Prisma.SeatClassScalarFieldEnum | Prisma.SeatClassScalarFieldEnum[]
}

/**
 * SeatClass create
 */
export type SeatClassCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatClass
   */
  select?: Prisma.SeatClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatClass
   */
  omit?: Prisma.SeatClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatClassInclude<ExtArgs> | null
  /**
   * The data needed to create a SeatClass.
   */
  data: Prisma.XOR<Prisma.SeatClassCreateInput, Prisma.SeatClassUncheckedCreateInput>
}

/**
 * SeatClass createMany
 */
export type SeatClassCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SeatClasses.
   */
  data: Prisma.SeatClassCreateManyInput | Prisma.SeatClassCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SeatClass createManyAndReturn
 */
export type SeatClassCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatClass
   */
  select?: Prisma.SeatClassSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SeatClass
   */
  omit?: Prisma.SeatClassOmit<ExtArgs> | null
  /**
   * The data used to create many SeatClasses.
   */
  data: Prisma.SeatClassCreateManyInput | Prisma.SeatClassCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SeatClass update
 */
export type SeatClassUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatClass
   */
  select?: Prisma.SeatClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatClass
   */
  omit?: Prisma.SeatClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatClassInclude<ExtArgs> | null
  /**
   * The data needed to update a SeatClass.
   */
  data: Prisma.XOR<Prisma.SeatClassUpdateInput, Prisma.SeatClassUncheckedUpdateInput>
  /**
   * Choose, which SeatClass to update.
   */
  where: Prisma.SeatClassWhereUniqueInput
}

/**
 * SeatClass updateMany
 */
export type SeatClassUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SeatClasses.
   */
  data: Prisma.XOR<Prisma.SeatClassUpdateManyMutationInput, Prisma.SeatClassUncheckedUpdateManyInput>
  /**
   * Filter which SeatClasses to update
   */
  where?: Prisma.SeatClassWhereInput
  /**
   * Limit how many SeatClasses to update.
   */
  limit?: number
}

/**
 * SeatClass updateManyAndReturn
 */
export type SeatClassUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatClass
   */
  select?: Prisma.SeatClassSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SeatClass
   */
  omit?: Prisma.SeatClassOmit<ExtArgs> | null
  /**
   * The data used to update SeatClasses.
   */
  data: Prisma.XOR<Prisma.SeatClassUpdateManyMutationInput, Prisma.SeatClassUncheckedUpdateManyInput>
  /**
   * Filter which SeatClasses to update
   */
  where?: Prisma.SeatClassWhereInput
  /**
   * Limit how many SeatClasses to update.
   */
  limit?: number
}

/**
 * SeatClass upsert
 */
export type SeatClassUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatClass
   */
  select?: Prisma.SeatClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatClass
   */
  omit?: Prisma.SeatClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatClassInclude<ExtArgs> | null
  /**
   * The filter to search for the SeatClass to update in case it exists.
   */
  where: Prisma.SeatClassWhereUniqueInput
  /**
   * In case the SeatClass found by the `where` argument doesn't exist, create a new SeatClass with this data.
   */
  create: Prisma.XOR<Prisma.SeatClassCreateInput, Prisma.SeatClassUncheckedCreateInput>
  /**
   * In case the SeatClass was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SeatClassUpdateInput, Prisma.SeatClassUncheckedUpdateInput>
}

/**
 * SeatClass delete
 */
export type SeatClassDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatClass
   */
  select?: Prisma.SeatClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatClass
   */
  omit?: Prisma.SeatClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatClassInclude<ExtArgs> | null
  /**
   * Filter which SeatClass to delete.
   */
  where: Prisma.SeatClassWhereUniqueInput
}

/**
 * SeatClass deleteMany
 */
export type SeatClassDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SeatClasses to delete
   */
  where?: Prisma.SeatClassWhereInput
  /**
   * Limit how many SeatClasses to delete.
   */
  limit?: number
}

/**
 * SeatClass.seats
 */
export type SeatClass$seatsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seat
   */
  select?: Prisma.SeatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seat
   */
  omit?: Prisma.SeatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatInclude<ExtArgs> | null
  where?: Prisma.SeatWhereInput
  orderBy?: Prisma.SeatOrderByWithRelationInput | Prisma.SeatOrderByWithRelationInput[]
  cursor?: Prisma.SeatWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SeatScalarFieldEnum | Prisma.SeatScalarFieldEnum[]
}

/**
 * SeatClass without action
 */
export type SeatClassDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatClass
   */
  select?: Prisma.SeatClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SeatClass
   */
  omit?: Prisma.SeatClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatClassInclude<ExtArgs> | null
}
