
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model Customer
 * 
 */
export type Customer = Prisma.CustomerModel
/**
 * Model Staff
 * 
 */
export type Staff = Prisma.StaffModel
/**
 * Model Order
 * 
 */
export type Order = Prisma.OrderModel
/**
 * Model Method
 * 
 */
export type Method = Prisma.MethodModel
/**
 * Model Shift
 * 
 */
export type Shift = Prisma.ShiftModel
/**
 * Model Ticket
 * 
 */
export type Ticket = Prisma.TicketModel
/**
 * Model Seat
 * 
 */
export type Seat = Prisma.SeatModel
/**
 * Model SeatClass
 * 
 */
export type SeatClass = Prisma.SeatClassModel
/**
 * Model Trip
 * 
 */
export type Trip = Prisma.TripModel
