
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const SeatStatus = {
  Available: 'Available',
  Booked: 'Booked',
  Unavailable: 'Unavailable'
} as const

export type SeatStatus = (typeof SeatStatus)[keyof typeof SeatStatus]


export const TicketStatus = {
  Open: 'Open',
  Resolved: 'Resolved'
} as const

export type TicketStatus = (typeof TicketStatus)[keyof typeof TicketStatus]


export const OrderStatus = {
  Pending: 'Pending',
  Confirmed: 'Confirmed',
  Denied: 'Denied'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]
