
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Customer.js'
export type * from './models/Staff.js'
export type * from './models/Order.js'
export type * from './models/Method.js'
export type * from './models/Shift.js'
export type * from './models/Ticket.js'
export type * from './models/Seat.js'
export type * from './models/Trip.js'
export type * from './commonInputTypes.js'